package server

import (
	"fmt"
	"strings"

	"github.com/langgenius/dify-go/internal/state"
)

func buildPreviewEstimateOutputs(docForm, datasourceType string, datasourceInfoList []map[string]any, processRule state.DatasetProcessRule) map[string]any {
	normalizedDocForm := firstNonEmpty(strings.TrimSpace(docForm), "text_model")
	items := cloneMapList(datasourceInfoList)
	if len(items) == 0 {
		items = []map[string]any{{}}
	}

	preview := make([]map[string]any, 0, len(items))
	qaPreview := make([]map[string]any, 0, len(items)*2)
	parentMode := firstNonEmpty(strings.TrimSpace(processRule.Rules.ParentMode), "paragraph")

	for index, item := range items {
		label := previewSourceLabel(datasourceType, item, index)
		summary := fmt.Sprintf("Compatibility summary for %s.", label)

		switch normalizedDocForm {
		case "hierarchical_model":
			preview = append(preview, map[string]any{
				"content":      fmt.Sprintf("Parent chunk %d extracted from %s.", index+1, label),
				"child_chunks": previewChildChunks(label, parentMode, index),
				"summary":      summary,
			})
		case "qa_model":
			for qaIndex := 0; qaIndex < 2; qaIndex++ {
				question := fmt.Sprintf("What does %s cover in preview section %d?", label, qaIndex+1)
				answer := fmt.Sprintf("%s preview answer %d generated by the dify-go QA compatibility layer.", label, qaIndex+1)
				qaPreview = append(qaPreview, map[string]any{
					"question": question,
					"answer":   answer,
				})
				preview = append(preview, map[string]any{
					"content":      question,
					"child_chunks": []string{},
					"summary":      answer,
				})
			}
		default:
			preview = append(preview, map[string]any{
				"content":      fmt.Sprintf("Preview chunk %d extracted from %s by the dify-go dataset compatibility layer.", index+1, label),
				"child_chunks": []string{},
				"summary":      summary,
			})
		}
	}

	totalSegments := len(preview)
	if normalizedDocForm == "qa_model" {
		totalSegments = len(qaPreview)
	}

	outputs := map[string]any{
		"chunk_structure": normalizedDocForm,
		"total_nodes":     len(items),
		"tokens":          totalSegments * 128,
		"total_price":     0,
		"currency":        "USD",
		"total_segments":  totalSegments,
		"preview":         preview,
	}
	if normalizedDocForm == "hierarchical_model" {
		outputs["parent_mode"] = parentMode
	}
	if normalizedDocForm == "qa_model" {
		outputs["qa_preview"] = qaPreview
	}
	return outputs
}

func previewChildChunks(label, parentMode string, index int) []string {
	if strings.TrimSpace(parentMode) == "full-doc" {
		return []string{
			fmt.Sprintf("Context slice A from %s.", label),
			fmt.Sprintf("Context slice B from %s.", label),
			fmt.Sprintf("Context slice C from %s.", label),
			fmt.Sprintf("Context slice D from %s.", label),
		}
	}

	return []string{
		fmt.Sprintf("Paragraph child chunk %d.1 from %s.", index+1, label),
		fmt.Sprintf("Paragraph child chunk %d.2 from %s.", index+1, label),
		fmt.Sprintf("Paragraph child chunk %d.3 from %s.", index+1, label),
	}
}

func previewSourceLabel(datasourceType string, info map[string]any, index int) string {
	switch strings.TrimSpace(datasourceType) {
	case "local_file":
		return firstNonEmpty(
			stringFromAny(info["name"]),
			stringFromAny(mapFromAny(info["upload_file"])["name"]),
			fmt.Sprintf("local file %d", index+1),
		)
	case "online_document", "notion_import":
		page := mapFromAny(info["page"])
		return firstNonEmpty(
			stringFromAny(page["page_name"]),
			stringFromAny(info["page_name"]),
			stringFromAny(info["page_id"]),
			fmt.Sprintf("notion page %d", index+1),
		)
	case "website_crawl":
		return firstNonEmpty(
			stringFromAny(info["title"]),
			stringFromAny(info["source_url"]),
			fmt.Sprintf("website page %d", index+1),
		)
	case "online_drive":
		return firstNonEmpty(
			stringFromAny(info["name"]),
			stringFromAny(info["id"]),
			fmt.Sprintf("drive file %d", index+1),
		)
	default:
		return firstNonEmpty(
			stringFromAny(info["name"]),
			stringFromAny(info["title"]),
			stringFromAny(info["related_id"]),
			fmt.Sprintf("datasource item %d", index+1),
		)
	}
}

func datasetPreviewDatasourceItems(dataSourceType string, infoList map[string]any) []map[string]any {
	switch strings.TrimSpace(dataSourceType) {
	case "notion_import":
		items := make([]map[string]any, 0)
		for _, entry := range anySlice(infoList["notion_info_list"]) {
			notionInfo := mapFromAny(entry)
			for _, pageValue := range anySlice(notionInfo["pages"]) {
				items = append(items, map[string]any{
					"workspace_id":  stringFromAny(notionInfo["workspace_id"]),
					"credential_id": stringFromAny(notionInfo["credential_id"]),
					"page":          mapFromAny(pageValue),
				})
			}
		}
		return items
	case "website_crawl":
		websiteInfo := mapFromAny(infoList["website_info_list"])
		items := make([]map[string]any, 0)
		for _, value := range anySlice(websiteInfo["urls"]) {
			sourceURL := stringFromAny(value)
			items = append(items, map[string]any{
				"provider":   stringFromAny(websiteInfo["provider"]),
				"job_id":     stringFromAny(websiteInfo["job_id"]),
				"source_url": sourceURL,
				"title":      sourceURL,
			})
		}
		return items
	default:
		fileInfo := mapFromAny(infoList["file_info_list"])
		items := make([]map[string]any, 0)
		for _, value := range anySlice(fileInfo["file_ids"]) {
			fileID := stringFromAny(value)
			items = append(items, map[string]any{
				"related_id": fileID,
				"name":       firstNonEmpty(fileID, fmt.Sprintf("uploaded file %d", len(items)+1)),
			})
		}
		return items
	}
}
